### ISSUE TITLE
First stat is overflowing into the second one

### ISSUE THREAD

**Issue by makurj** [uiowa/viewbook-law#17]
At differente viewports, the first stat in the first stats bar is not lining correctly. 
![image](https://user-images.githubusercontent.com/52135878/133275314-6609c993-df79-4ff2-8388-4b676a3a8c17.png)

![image](https://user-images.githubusercontent.com/52135878/133275368-28f36736-9b0c-4b70-a59f-493aae1ad25f.png)

**Comment by bspeare** [comment]
I think this overflow depends on the character count for each stat.   I think the fix for this would be to either change it to 3 columns of stats or break the display into a stacked grid at a higher breakpoint.

**Comment by bspeare** [comment]
Resolved via https://github.com/uiowa/viewbook-law/pull/24
