### ISSUE TITLE
Content changes to Law Viewbook

### ISSUE THREAD

**Issue by briand44** [uiowa/viewbook-law#28]
Copy:
- https://iowa-my.sharepoint.com/:w:/g/personal/bspeare_uiowa_edu/EQxGip8K-e5DqA0W0vBgq30BmVvdhJ1uRJ2kI_BcB39H5g?e=LA3c2L

Images:

- [1.zip](https://github.com/uiowa/uiowa/files/9649399/1.zip)
- [2.zip](https://github.com/uiowa/uiowa/files/9649402/2.zip)
- [3.zip](https://github.com/uiowa/uiowa/files/9649404/3.zip)

**Comment by joewhitsitt** [comment]
Is this issue resolved?

**Comment by makurj** [comment]
Blocked/waiting until approval from Law.
