### ISSUE TITLE
Updates to Law Viewbook site

### ISSUE THREAD

**Issue by mjoneill** [uiowa/viewbook-law#6]
Design partners requesting the following edits/changes to the Law viewbook site before we can release it to the College of Law for review:  

- [x] Update main photo (see attached below)
- [x] Can we go ahead and set up button links so law can confirm those go to the right places? URLs are included in word document attached below.
- [x]  Update text in buttons to be action-orientAd:
> - [x] Academics → View our Curriculum
> - [x] Faculty and Scholarship → Meet our Faculty
> - [x] Experiential Learning → Explore Experiential Opportunities
> - [x] Student Life → Discover Iowa City
> - [x] Careers → Learn About Career Services
- [x] Can text be vertically centered in their blocks?
- [x] Can we get some visual separation between the profiles and footer? Perhaps giving the profiles have a White or light grey BG would help?
- [x] Add Header above profiles: "See what students are saying about Iowa Law"
- [x] Set up GA and GTM on site

**Comment by makurj** [comment]
All changes except GTM, GA made. User can view them here: https://viewbook.law.uiowa.edu/latest/

**Comment by makurj** [comment]
All tasks completed. Closing issue.
